name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build production project
        run: yarn run build:prod
      - name: unit testing
        run: yarn run test:unit
      - name: lint testing
        run: yarn run lint
      - name: build storybook
        run: yarn run storybook:build
      - name: screenshot testing
        run: yarn run test:ui:ci
      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: design-system
          path: .loki