name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build production project
        run: yarn build:prod
      - name: unit testing
        run: yarn test:unit
      - name: lint testing
        run: yarn lint
      - name: build storybook
        run: yarn storybook:build
      - name: screenshot testing
        run: yarn test:ui:ci
      - name: screenshot testing approve
        run: yarn test:ui:approve